name: "Snyk Github Action"
# Run workflow each time code is pushed to your repository.
on: push
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: install snyk-to-html
       run: |
         npm install snyk-to-html -g
     - uses: actions/checkout@v2
     - uses: snyk/actions/setup@master
     - name: Snyk Test
       run: snyk test --sarif-file-output=snyk-sarif.json
            snyk test --json | snyk-to-html -o result-vuln.html
       continue-on-error: true       
       env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
          
     - name: Upload SARIF file
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: snyk-sarif.json

     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v2
       with:
         name: result-vuln.html
         path: output/result-vuln.html
         retention-days: 5
